version: '3.8'

services:
  api:
    container_name: cloudnest-api
    image: cloudnest-api:1.0.0
    build:
      context: .
      target: development
    command: npm run start:debug api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
  micro:
    container_name: cloudnest-micro
    image: cloudnest-micro:1.0.0
    build:
      context: .
      target: development
    command: npm run start:debug micro
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${MICRO_PORT}:${MICRO_PORT}
    env_file:
      - .env
  db:
    container_name: cloudnest-db
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
